---
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install pip
  yum:
    name: python-pip
    state: present

- name: Install python jsondiff
  pip:
    name: jsondiff

- name: Install python docker-py
  pip:
    name: docker-py

- name: Install python pyyaml
  pip:
    name: pyyaml

- include_tasks: docker-install.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

# TODO: Remove this shim once 18.09.1 or later is released.
- import_tasks: docker-systemd-service.yml
  when: ansible_service_mgr == 'systemd'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: Create data directory for prometheus
  file:
    state: directory
    path: /prometheus
    mode: 0777

- name: uplodad docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "/prometheus/docker-compose.yml"

- name: copy directory
  copy:
    src: ./configs/
    dest: "/prometheus/configs/"

- name: Run docker compose
  command: docker-compose up -d
  args:
    chdir: /prometheus
  become: yes
  become_user: root

- debug:
    var: output
